---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# layer

<!-- badges: start -->
<!-- badges: end -->

The goal of layer is to ...

## Installation

You can install the development version of layer from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("marcosci/layer")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example, echo = FALSE}
library(layer)
library(ggplot2)
library(scico)

tilt_landscape_1 <- tilt_map(landscape_1)
tilt_landscape_2 <- tilt_map(landscape_2, x_shift = 50, y_shift = 50)
tilt_landscape_3 <- tilt_map(landscape_3, x_shift = 100, y_shift = 100)
tilt_landscape_points <- tilt_map(landscape_points, x_shift = 150, y_shift = 150)

ggplot() +
  geom_sf(data = tilt_landscape_1,
          aes(fill = layer), color = NA) +
  geom_sf(data = tilt_landscape_2,
          aes(fill = layer), color = NA) +
  geom_sf(data = tilt_landscape_3,
          aes(fill = layer), color = NA) +
  geom_sf(data = tilt_landscape_points,
          color = "red") +
  scale_fill_scico(palette = 'davos') +
  theme(legend.position = "none") +
  theme_void()
```
